# Generated by Django 3.0.5 on 2020-04-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200427_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='oldPrice',
        ),
    ]
