# Generated by Django 3.0.5 on 2020-04-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_product_oldprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='econom',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shortDesc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
