# Generated by Django 3.0.5 on 2020-04-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200427_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='econom',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='oldPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shortDesc',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=300),
        ),
    ]
