# Generated by Django 3.0.5 on 2020-04-27 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200427_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='oldPrice',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
